# Generated by Django 6.0.3 on 2026-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishpond',
            name='fish_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fishpond',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fishpond',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
