# Generated by Django 6.0.3 on 2026-05-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0002_fishpond_fish_type_fishpond_location_fishpond_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishpond',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishpond',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('harvesting', 'Harvesting'), ('maintenance', 'Maintenance'), ('empty', 'Empty')], default='active', max_length=20),
        ),
    ]
