# Generated by Django 6.0.4 on 2026-06-02 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0003_fishpond_notes_fishpond_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fishpond',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishpond',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harvest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishpond',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('empty', 'Empty')], default='active', max_length=20),
        ),
    ]
