# Generated by Django 6.0.4 on 2026-06-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0004_fishpond_created_at_fishpond_stock_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='user',
        ),
    ]
