# Generated by Django 6.0.4 on 2026-06-13 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_harvest_fish_types(apps, schema_editor):
    """Migrate existing CharField fish_type values to ForeignKey references"""
    FishType = apps.get_model('arich_app', 'FishType')
    Harvest = apps.get_model('arich_app', 'Harvest')
    
    # Get unique fish type names from Harvest records
    fish_type_names = set()
    for harvest in Harvest.objects.all():
        if harvest.fish_type:
            fish_type_names.add(harvest.fish_type.strip())
    
    # Create or get FishType entries
    name_to_id = {}
    for name in fish_type_names:
        if name:
            ft, _ = FishType.objects.get_or_create(name=name)
            name_to_id[name] = ft.id
    
    # Update Harvest records using raw SQL since column type is changing
    if name_to_id:
        with schema_editor.connection.cursor() as cursor:
            for name, ft_id in name_to_id.items():
                cursor.execute(
                    "UPDATE arich_app_harvest SET fish_type = %s WHERE fish_type = %s",
                    [ft_id, name]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0005_remove_harvest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create FishType model first
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fish Types',
                'ordering': ['name'],
            },
        ),
        
        # Create FishpondFishType model
        migrations.CreateModel(
            name='FishpondFishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_types', to='arich_app.fishpond')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='arich_app.fishtype')),
            ],
            options={
                'verbose_name_plural': 'Fishpond Fish Types',
                'ordering': ['fish_type__name'],
                'unique_together': {('pond', 'fish_type')},
            },
        ),
        
        # Migrate existing Harvest.fish_type data and create FishType entries
        migrations.RunPython(migrate_harvest_fish_types),
        
        # Update model options
        migrations.AlterModelOptions(
            name='fishpond',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-date']},
        ),
        
        # Remove old fields from Fishpond
        migrations.RemoveField(
            model_name='fishpond',
            name='fish_type',
        ),
        migrations.RemoveField(
            model_name='fishpond',
            name='stock_count',
        ),
        
        # Add new fields to Fishpond and Harvest
        migrations.AddField(
            model_name='fishpond',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Update relationship fields
        migrations.AlterField(
            model_name='fishpond',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishponds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='arich_app.fishpond'),
        ),
        
        # Convert Harvest.fish_type from CharField to ForeignKey
        migrations.AlterField(
            model_name='harvest',
            name='fish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arich_app.fishtype'),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='fishpond',
            index=models.Index(fields=['owner', '-created_at'], name='arich_app_f_owner_i_2b8f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['pond', '-date'], name='arich_app_h_pond_id_772bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['fish_type', '-date'], name='arich_app_h_fish_ty_74f690_idx'),
        ),
        migrations.AddIndex(
            model_name='fishpondfishtype',
            index=models.Index(fields=['pond'], name='arich_app_f_pond_id_2df871_idx'),
        ),
        migrations.AddIndex(
            model_name='fishpondfishtype',
            index=models.Index(fields=['fish_type'], name='arich_app_f_fish_ty_1bbc9e_idx'),
        ),
    ]
