# Generated by Django 6.0.3 on 2026-06-26 12:40

import arich_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arich_app', '0006_fishpondfishtype_fishtype_alter_fishpond_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fishtype',
            name='user',
            field=models.ForeignKey(default=arich_app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='fishtype',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='fishtype',
            name='description',
        ),
    ]
